# ==========================================
# SCP DEPARTMENTS
# ==========================================

- type: department
  id: SCPClassD
  name: department-SCPClassD
  description: department-SCPClassD-description
  color: "#CC5200"
  roles:
  - SCPClassD

- type: department
  id: SCPCommand
  name: department-SCPCommand
  description: department-SCPCommand-description
  color: "#B8971F"
  roles:
  - SCPSiteDirector
  - SCPSiteManager
  - SCPCommunicationsOfficer
  - SCPISDDetective
  - SCPEthicsCommittee
  - SCPGOCRepresentative
  - SCPCommsTechnician

- type: department
  id: SCPEngineering
  name: department-SCPEngineering
  description: department-SCPEngineering-description
  color: "#D4A017"
  roles:
  - SCPEngineeringDirector
  - SCPAsstEngDirector
  - SCPContainmentEngineer
  - SCPSeniorEngineer
  - SCPEngineer
  - SCPJuniorEngineer

- type: department
  id: SCPMedical
  name: department-SCPMedical
  description: department-SCPMedical-description
  color: "#008B6B"
  roles:
  - SCPMedicalDirector
  - SCPAsstMedDirector
  - SCPSurgeon
  - SCPChemist
  - SCPPsychiatrist
  - SCPMedicalDoctor
  - SCPEMT
  - SCPMedicalIntern

- type: department
  id: SCPLogistics
  name: department-SCPLogistics
  description: department-SCPLogistics-description
  color: "#9E8644"
  roles:
  - SCPLogisticsOfficer
  - SCPLogisticsSpecialist
  - SCPOfficeWorker
  - SCPBartender
  - SCPChaplain

- type: department
  id: SCPScience
  name: department-SCPScience
  description: department-SCPScience-description
  color: "#AA44AA"
  roles:
  - SCPResearchDirector
  - SCPSeniorResearcher
  - SCPSeniorRobotics
  - SCPResearcher
  - SCPRoboticsTechnician
  - SCPResearcherAssociate
  - SCPJuniorRobotics

- type: department
  id: SCPSecurity
  name: department-SCPSecurity
  description: department-SCPSecurity-description
  color: "#AA1515"
  roles:
  - SCPGuardCommander
  - SCPLCZJuniorLt
  - SCPHCZSeniorLt
  - SCPEZSupervisor
  - SCPRAISAAgent
  - SCPLCZSergeant
  - SCPHCZSergeant
  - SCPEZSeniorAgent
  - SCPLCZGuard
  - SCPHCZGuard
  - SCPEZAgent
  - SCPLCZCadet
  - SCPHCZPrivate
  - SCPEZProbAgent

- type: department
  id: SCPSpecial
  name: department-SCPSpecial
  description: department-SCPSpecial-description
  color: "#336633"
  roles:
  - SCPAIC
  - SCPRobot
  - SCPO5Council
  - SCPMTFE11Commander
  - SCPMTFE11Lieutenant
  - SCPMTFE11Sergeant
  - SCPMTFE11Agent
  - SCPMTFNU7Commander
  - SCPMTFNU7Lieutenant
  - SCPMTFNU7Agent

