# ==========================================
# SCP DEPARTMENTS
# ==========================================

- type: department
  id: SCPClassD
  name: "f14-class-d-personnel"
  description: "f14-department-class-d-desc"
  color: "#CC5200"
  roles:
  - SCPClassD

- type: department
  id: SCPCommand
  name: "f14-department-administration-name"
  description: "f14-department-administration-desc"
  color: "#B8971F"
  roles:
  - SCPSiteDirector
  - SCPSiteManager
  - SCPCommunicationsOfficer
  - SCPISDDetective
  - SCPEthicsCommittee
  - SCPGOCRepresentative
  - SCPCommsTechnician

- type: department
  id: SCPEngineering
  name: "f14-department-engineering-name"
  description: "f14-department-engineering-desc"
  color: "#D4A017"
  roles:
  - SCPEngineeringDirector
  - SCPAsstEngDirector
  - SCPContainmentEngineer
  - SCPSeniorEngineer
  - SCPEngineer
  - SCPJuniorEngineer

- type: department
  id: SCPMedical
  name: "f14-department-medical-name"
  description: "f14-department-medical-desc"
  color: "#008B6B"
  roles:
  - SCPMedicalDirector
  - SCPAsstMedDirector
  - SCPSurgeon
  - SCPChemist
  - SCPPsychiatrist
  - SCPMedicalDoctor
  - SCPEMT
  - SCPMedicalIntern

- type: department
  id: SCPLogistics
  name: "f14-department-logistics-name"
  description: "f14-department-logistics-desc"
  color: "#9E8644"
  roles:
  - SCPLogisticsOfficer
  - SCPLogisticsSpecialist
  - SCPOfficeWorker
  - SCPBartender
  - SCPChaplain

- type: department
  id: SCPScience
  name: "f14-department-research-name"
  description: "f14-department-research-desc"
  color: "#AA44AA"
  roles:
  - SCPResearchDirector
  - SCPSeniorResearcher
  - SCPSeniorRobotics
  - SCPResearcher
  - SCPRoboticsTechnician
  - SCPResearcherAssociate
  - SCPJuniorRobotics

- type: department
  id: SCPSecurity
  name: "f14-department-security-name"
  description: "f14-department-security-desc"
  color: "#AA1515"
  roles:
  - SCPGuardCommander
  - SCPLCZJuniorLt
  - SCPHCZSeniorLt
  - SCPEZSupervisor
  - SCPRAISAAgent
  - SCPLCZSergeant
  - SCPHCZSergeant
  - SCPEZSeniorAgent
  - SCPLCZGuard
  - SCPHCZGuard
  - SCPEZAgent
  - SCPLCZCadet
  - SCPHCZPrivate
  - SCPEZProbAgent

- type: department
  id: SCPSpecial
  name: "f14-department-special-name"
  description: "f14-department-special-desc"
  color: "#336633"
  roles:
  - SCPAIC
  - SCPRobot